name: kingdom
description: A gamified finance + fitness kingdom tracker
publish_to: "none" # not publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^1.0.0
  intl: ^0.19.0

  # You can add more deps later (animations, storage, firebase, etc.)
  # Example: shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hex_grass.png
    - assets/images/hex_grass_active.png
    - assets/images/keep.png
    - assets/images/map_underlay.png
