name: kingdom
description: A gamified finance + fitness kingdom tracker
publish_to: "none" # not publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^1.0.0
  intl: ^0.20.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4
  qr_flutter: ^4.1.0
  qr: ^3.0.2
  cloud_functions: ^5.6.2
  mobile_scanner: ^7.0.1
  uuid: ^3.0.6

  # You can add more deps later (animations, storage, firebase, etc.)
  # Example: shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hex_grass.png
    - assets/images/hex_grass_active.png
    - assets/images/keep.png
    - assets/images/map_underlay.png
    - assets/images/shack.png
    - assets/images/map_underlay2.png
    - assets/images/map_underlay3.png
    - assets/images/portraits/Gemini_Generated_Image_jxdhrijxdhrijxdh.png
    - assets/images/portraits/Gemini_Generated_Image_ldt41vldt41vldt4.png
    - assets/images/portraits/Gemini_Generated_Image_rgtie3rgtie3rgti.png
    - assets/images/portraits/Gemini_Generated_Image_u5ou4lu5ou4lu5ou.png
    - assets/images/portraits/Gemini_Generated_Image_xgeshlxgeshlxges.png
