// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKjOcKBRSbCQsISoPiviFfx9uufHXOiY',
    appId: '1:968566097636:web:0f4e1631ed7b03115a0ef1',
    messagingSenderId: '968566097636',
    projectId: 'kingdom-ac44f',
    authDomain: 'kingdom-ac44f.firebaseapp.com',
    databaseURL: 'https://kingdom-ac44f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingdom-ac44f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5K8_jbh-95R78mz8mp2YunY7wHnIbxWk',
    appId: '1:968566097636:android:f561d9a981d215d25a0ef1',
    messagingSenderId: '968566097636',
    projectId: 'kingdom-ac44f',
    databaseURL: 'https://kingdom-ac44f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingdom-ac44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvmJ5rZM8ojrcmnZO6vWmDDAfAlZLPL8M',
    appId: '1:968566097636:ios:e42d88ff9bd863375a0ef1',
    messagingSenderId: '968566097636',
    projectId: 'kingdom-ac44f',
    databaseURL: 'https://kingdom-ac44f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kingdom-ac44f.firebasestorage.app',
    androidClientId: '968566097636-k57sugq9hs5c85t7gfelcpv93mubk38f.apps.googleusercontent.com',
    iosClientId: '968566097636-910urtjnmt9i6u3fgv1h71tusp392hvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kingdom',
  );
}
